# Generated by Django 2.0.3 on 2020-04-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_item_id', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('offer_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.IntegerField()),
                ('shipment_date', models.DateField()),
                ('transport_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.ShipmentRetailer'),
        ),
    ]
