# Generated by Django 2.0.3 on 2020-04-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200426_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='fulfilment_method',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
