# Generated by Django 2.0.3 on 2020-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_shipmentitem_fulfilment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentretailer',
            name='shipment_date',
            field=models.DateTimeField(),
        ),
    ]
