# Generated by Django 2.0.3 on 2020-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_auto_20200426_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
