# Generated by Django 2.0.3 on 2020-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20200426_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='offer_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_item_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
